language: node_js

node_js:
  - 11
  - 10
before_script:
  - npm run danger
jobs:

  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
    # node_js: 10
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - codecov ./coverage/ && npx semantic-release
